/**
 * Grant Scoring Engine — Hard-coded mathematical scoring.
 * Match percentages are NEVER generated by Claude.
 * Claude structures the raw grant data; this function scores it.
 */

// ---- NAICS adjacency map (top-level 2-digit sector codes) ----
const NAICS_SECTORS = {
  '11': 'Agriculture',
  '21': 'Mining',
  '22': 'Utilities',
  '23': 'Construction',
  '31': 'Manufacturing', '32': 'Manufacturing', '33': 'Manufacturing',
  '42': 'Wholesale Trade',
  '44': 'Retail Trade', '45': 'Retail Trade',
  '48': 'Transportation', '49': 'Transportation',
  '51': 'Information/Tech',
  '52': 'Finance/Insurance',
  '53': 'Real Estate',
  '54': 'Professional/Scientific/Technical Services',
  '55': 'Management',
  '56': 'Administrative/Waste Services',
  '61': 'Education',
  '62': 'Healthcare/Social',
  '71': 'Arts/Entertainment/Recreation',
  '72': 'Accommodation/Food Services',
  '81': 'Other Services',
  '92': 'Public Administration'
};

// Adjacent sectors (if member is in sector A, grants for sector B are "adjacent")
const ADJACENT_SECTORS = {
  '54': ['51', '55', '56'], // Professional services ↔ Tech, Management, Admin
  '51': ['54', '33'],       // Tech ↔ Professional, Manufacturing (hardware)
  '23': ['31', '32', '33'], // Construction ↔ Manufacturing
  '31': ['23', '32', '33'], // Manufacturing ↔ Construction, other manufacturing
  '32': ['23', '31', '33'],
  '33': ['23', '31', '32', '51'],
  '44': ['45', '42'],       // Retail ↔ Wholesale
  '45': ['44', '42'],
  '42': ['44', '45'],
  '72': ['71'],              // Food services ↔ Entertainment
  '71': ['72'],
  '62': ['61'],              // Healthcare ↔ Education
  '61': ['62']
};

// ---- Industry keyword matching ----
const INDUSTRY_KEYWORDS = {
  'software': ['51', '54'],
  'ai': ['51', '54'],
  'saas': ['51', '54'],
  'tech': ['51', '54'],
  'platform': ['51', '54'],
  'app': ['51', '54'],
  'consulting': ['54'],
  'advisory': ['54'],
  'professional services': ['54'],
  'construction': ['23'],
  'contractor': ['23'],
  'trades': ['23'],
  'plumbing': ['23'],
  'electrical': ['23'],
  'hvac': ['23'],
  'manufacturing': ['31', '32', '33'],
  'retail': ['44', '45'],
  'restaurant': ['72'],
  'food': ['72'],
  'catering': ['72'],
  'healthcare': ['62'],
  'medical': ['62'],
  'education': ['61'],
  'training': ['61'],
  'real estate': ['53'],
  'landscaping': ['56'],
  'cleaning': ['56'],
  'agriculture': ['11'],
  'farming': ['11'],
  'transportation': ['48', '49'],
  'trucking': ['48', '49'],
  'logistics': ['48', '49'],
  'finance': ['52'],
  'insurance': ['52'],
  'nonprofit': ['81', '62', '61'],
  'arts': ['71'],
  'entertainment': ['71'],
  'media': ['51']
};

/**
 * Extract the 2-digit NAICS sector from a NAICS code string.
 */
function getNAICSSector(naicsCode) {
  if (!naicsCode) return null;
  const cleaned = String(naicsCode).replace(/\D/g, '');
  return cleaned.substring(0, 2) || null;
}

/**
 * Infer likely NAICS sectors from business description and type.
 */
function inferNAICSSectors(businessType, businessDescription) {
  const combined = ((businessType || '') + ' ' + (businessDescription || '')).toLowerCase();
  const sectors = new Set();

  for (const [keyword, codes] of Object.entries(INDUSTRY_KEYWORDS)) {
    if (combined.includes(keyword)) {
      codes.forEach(c => sectors.add(c));
    }
  }

  return Array.from(sectors);
}

/**
 * Normalize entity type strings for comparison.
 */
function normalizeEntityType(type) {
  if (!type) return '';
  const lower = type.toLowerCase().trim();

  if (lower.includes('sole') || lower.includes('proprietor')) return 'sole_proprietorship';
  if (lower.includes('llc')) return 'llc';
  if (lower.includes('s-corp') || lower.includes('s corp') || lower.includes('s_corp')) return 's_corp';
  if (lower.includes('c-corp') || lower.includes('c corp') || lower.includes('c_corp')) return 'c_corp';
  if (lower.includes('501') || lower.includes('nonprofit') || lower.includes('non-profit')) return 'nonprofit';
  if (lower.includes('partnership')) return 'partnership';
  if (lower.includes('not yet') || lower.includes('not registered')) return 'unregistered';

  return lower;
}

/**
 * Check if a state abbreviation or name matches a grant's location requirements.
 */
function stateMatches(memberState, grantLocations) {
  if (!grantLocations || grantLocations.length === 0) return 'nationwide';
  if (!memberState) return 'no_match';

  const memberStateLower = memberState.toLowerCase().trim();

  for (const loc of grantLocations) {
    const locLower = (loc || '').toLowerCase().trim();
    if (locLower === 'nationwide' || locLower === 'national' || locLower === 'all states' || locLower === 'all') {
      return 'nationwide';
    }
    if (locLower === memberStateLower) return 'match';
    // Check abbreviation vs full name
    if (locLower.length === 2 && locLower === memberStateLower) return 'match';
  }

  return 'no_match';
}

/**
 * THE SCORING FUNCTION
 *
 * calculateGrantMatch(memberProfile, grantCriteria)
 *
 * memberProfile: combined data from business basics + grant radar intake
 * grantCriteria: structured eligibility from a grant opportunity
 *
 * Returns: { totalScore, dimensions, excluded, exclusionReason, improvements }
 */
function calculateGrantMatch(memberProfile, grantCriteria) {
  const dimensions = {};
  let excluded = false;
  let exclusionReason = null;
  const improvements = [];

  // ---- 1. ENTITY TYPE MATCH — weight 15 ----
  const memberEntity = normalizeEntityType(memberProfile.legalStructure || memberProfile.legalEntity);
  const grantEntities = (grantCriteria.eligibleEntityTypes || []).map(normalizeEntityType);

  if (grantEntities.length === 0) {
    // Grant doesn't specify entity requirements — full score
    dimensions.entityType = { score: 15, max: 15, detail: 'No entity type restriction' };
  } else if (grantEntities.includes(memberEntity) || grantEntities.includes('any') || grantEntities.includes('all')) {
    dimensions.entityType = { score: 15, max: 15, detail: 'Entity type matches' };
  } else {
    dimensions.entityType = { score: 0, max: 15, detail: `Grant requires: ${grantEntities.join(', ')}. You are: ${memberEntity}` };
    excluded = true;
    exclusionReason = 'Entity type does not match grant requirements';
  }

  // ---- 2. REVENUE ELIGIBILITY — weight 20 ----
  const memberRevenue = parseInt(memberProfile.annualRevenue, 10) || 0;
  const revMin = grantCriteria.revenueMin != null ? parseInt(grantCriteria.revenueMin, 10) : null;
  const revMax = grantCriteria.revenueMax != null ? parseInt(grantCriteria.revenueMax, 10) : null;

  if (revMin == null && revMax == null) {
    // No revenue requirements
    dimensions.revenue = { score: 20, max: 20, detail: 'No revenue requirement' };
  } else {
    const withinMin = revMin == null || memberRevenue >= revMin;
    const withinMax = revMax == null || memberRevenue <= revMax;

    if (withinMin && withinMax) {
      dimensions.revenue = { score: 20, max: 20, detail: 'Revenue within eligible range' };
    } else if (revMax != null && memberRevenue > revMax) {
      // Check if within 20% of the cap
      const overBy = ((memberRevenue - revMax) / revMax) * 100;
      if (overBy <= 20) {
        dimensions.revenue = { score: 10, max: 20, detail: `Revenue $${memberRevenue.toLocaleString()} is ${overBy.toFixed(0)}% over cap of $${revMax.toLocaleString()}` };
        improvements.push({
          dimension: 'Revenue',
          text: `Your revenue ($${memberRevenue.toLocaleString()}) is slightly above this grant's cap of $${revMax.toLocaleString()}. If your revenue changes, you may become eligible.`,
          effort: 'Not actionable — depends on business revenue'
        });
      } else {
        dimensions.revenue = { score: 0, max: 20, detail: `Revenue $${memberRevenue.toLocaleString()} exceeds hard cap of $${revMax.toLocaleString()}` };
        excluded = true;
        exclusionReason = `Revenue exceeds grant cap of $${revMax.toLocaleString()}`;
      }
    } else if (revMin != null && memberRevenue < revMin) {
      const underBy = ((revMin - memberRevenue) / revMin) * 100;
      if (underBy <= 20) {
        dimensions.revenue = { score: 10, max: 20, detail: `Revenue $${memberRevenue.toLocaleString()} is ${underBy.toFixed(0)}% below minimum of $${revMin.toLocaleString()}` };
      } else {
        dimensions.revenue = { score: 0, max: 20, detail: `Revenue $${memberRevenue.toLocaleString()} below minimum of $${revMin.toLocaleString()}` };
      }
    }
  }

  // ---- 3. INDUSTRY / NAICS MATCH — weight 20 ----
  const memberNAICS = getNAICSSector(memberProfile.naicsCode);
  const inferredSectors = inferNAICSSectors(
    memberProfile.businessType || memberProfile.industry,
    memberProfile.businessDescription
  );
  const memberSectors = memberNAICS ? [memberNAICS, ...inferredSectors] : inferredSectors;

  const grantNAICS = (grantCriteria.eligibleNAICS || []).map(c => getNAICSSector(c)).filter(Boolean);
  const grantIndustryKeywords = (grantCriteria.eligibleIndustries || []).map(i => i.toLowerCase());

  if (grantNAICS.length === 0 && grantIndustryKeywords.length === 0) {
    dimensions.industry = { score: 20, max: 20, detail: 'No industry restriction' };
  } else {
    let industryMatch = 'none';

    // Check NAICS sector match
    for (const ms of memberSectors) {
      if (grantNAICS.includes(ms)) {
        industryMatch = 'direct';
        break;
      }
      // Check adjacency
      const adjacent = ADJACENT_SECTORS[ms] || [];
      for (const adj of adjacent) {
        if (grantNAICS.includes(adj)) {
          industryMatch = 'adjacent';
          break;
        }
      }
      if (industryMatch !== 'none') break;
    }

    // Check keyword match if NAICS didn't match
    if (industryMatch === 'none' && grantIndustryKeywords.length > 0) {
      const memberDesc = ((memberProfile.businessType || '') + ' ' + (memberProfile.businessDescription || '') + ' ' + (memberProfile.industry || '')).toLowerCase();
      for (const kw of grantIndustryKeywords) {
        if (memberDesc.includes(kw)) {
          industryMatch = 'direct';
          break;
        }
      }
    }

    if (industryMatch === 'direct') {
      dimensions.industry = { score: 20, max: 20, detail: 'Industry directly matches' };
    } else if (industryMatch === 'adjacent') {
      dimensions.industry = { score: 10, max: 20, detail: 'Adjacent industry match' };
      improvements.push({
        dimension: 'Industry',
        text: 'Your industry is adjacent but not an exact match for this grant. Review the grant requirements to confirm your business type qualifies.',
        effort: 'Quick check — 5 minutes reading grant eligibility'
      });
    } else {
      dimensions.industry = { score: 0, max: 20, detail: 'Industry does not match grant requirements' };
    }
  }

  // ---- 4. LOCATION ELIGIBILITY — weight 15 ----
  const memberState = memberProfile.state;
  const grantLocations = grantCriteria.eligibleLocations || [];
  const locationResult = stateMatches(memberState, grantLocations);

  if (locationResult === 'nationwide') {
    dimensions.location = { score: 15, max: 15, detail: 'Grant is available nationwide' };
  } else if (locationResult === 'match') {
    dimensions.location = { score: 15, max: 15, detail: 'Your state matches' };
  } else {
    dimensions.location = { score: 0, max: 15, detail: `Grant is limited to: ${grantLocations.join(', ')}. You are in: ${memberState}` };
    excluded = true;
    exclusionReason = `Grant not available in ${memberState}`;
  }

  // ---- 5. DEMOGRAPHIC BONUS — weight 10 ----
  const memberDemos = (memberProfile.ownerDemographics || []).map(d => d.toLowerCase());
  const grantDemoPriorities = (grantCriteria.demographicPriorities || []).map(d => d.toLowerCase());

  if (grantDemoPriorities.length === 0) {
    // No demographic priorities — give partial credit if member has any
    if (memberDemos.length > 0 && !memberDemos.includes('none') && !memberDemos.includes('none of the above')) {
      dimensions.demographic = { score: 5, max: 10, detail: 'You have eligible demographics; grant does not prioritize them' };
    } else {
      dimensions.demographic = { score: 5, max: 10, detail: 'No demographic priorities for this grant' };
    }
  } else {
    const hasMatch = grantDemoPriorities.some(gd =>
      memberDemos.some(md => md.includes(gd) || gd.includes(md))
    );
    if (hasMatch) {
      dimensions.demographic = { score: 10, max: 10, detail: 'Your demographics match grant priorities' };
    } else {
      dimensions.demographic = { score: 0, max: 10, detail: 'Grant prioritizes demographics you do not have' };
      improvements.push({
        dimension: 'Demographics',
        text: `This grant prioritizes: ${grantDemoPriorities.join(', ')}. This is not something you can change, but the grant may still accept applicants without these demographics.`,
        effort: 'Not actionable'
      });
    }
  }

  // ---- 6. SAM.GOV AND EIN STATUS — weight 10 ----
  const hasSAM = memberProfile.samRegistered === 'yes' || memberProfile.samRegistered === 'Yes';
  const hasEIN = memberProfile.hasEIN === 'yes' || memberProfile.hasEIN === 'Yes';
  const grantRequiresSAM = grantCriteria.requiresSAM !== false;
  const grantRequiresEIN = grantCriteria.requiresEIN !== false;

  let regScore = 10;
  const regIssues = [];

  if (grantRequiresSAM && !hasSAM) {
    regScore -= 5;
    regIssues.push('SAM.gov registration missing');
    improvements.push({
      dimension: 'Registration',
      text: 'Register on SAM.gov — free, takes about 30 minutes at sam.gov. Required before applying.',
      effort: '30 minutes'
    });
  }
  if (grantRequiresEIN && !hasEIN) {
    regScore -= 5;
    regIssues.push('EIN missing');
    improvements.push({
      dimension: 'Registration',
      text: 'Apply for an EIN — free, takes about 15 minutes at irs.gov/ein.',
      effort: '15 minutes'
    });
  }

  // Unsure counts as partial
  if (memberProfile.samRegistered === 'unsure' || memberProfile.samRegistered === 'I am not sure') {
    regScore = Math.min(regScore, 5);
    if (!regIssues.includes('SAM.gov registration missing')) {
      regIssues.push('SAM.gov status unclear');
    }
  }
  if (memberProfile.hasEIN === 'unsure' || memberProfile.hasEIN === 'I am not sure') {
    regScore = Math.min(regScore, 5);
    if (!regIssues.includes('EIN missing')) {
      regIssues.push('EIN status unclear');
    }
  }

  dimensions.registration = {
    score: Math.max(0, regScore),
    max: 10,
    detail: regIssues.length > 0 ? regIssues.join('; ') : 'All required registrations confirmed'
  };

  // ---- 7. FUND USE ALIGNMENT — weight 10 ----
  const memberFundUse = (memberProfile.primaryFundUse || '').toLowerCase();
  const grantEligibleUses = (grantCriteria.eligibleUses || []).map(u => u.toLowerCase());

  if (grantEligibleUses.length === 0) {
    dimensions.fundUse = { score: 10, max: 10, detail: 'No specific fund use requirement' };
  } else {
    const directMatch = grantEligibleUses.some(gu =>
      memberFundUse.includes(gu) || gu.includes(memberFundUse)
    );

    // Partial match keywords
    const fundUseKeywords = {
      'hiring': ['workforce', 'employees', 'staffing', 'team', 'jobs'],
      'equipment': ['technology', 'machinery', 'tools', 'purchasing'],
      'research': ['development', 'r&d', 'innovation'],
      'location': ['expansion', 'facility', 'building', 'lease'],
      'marketing': ['customer', 'acquisition', 'sales', 'outreach'],
      'training': ['workforce', 'education', 'skills', 'development'],
      'community': ['social', 'impact', 'program'],
      'operating': ['general', 'working capital', 'overhead'],
      'export': ['international', 'trade', 'global']
    };

    let partialMatch = false;
    if (!directMatch) {
      for (const [key, synonyms] of Object.entries(fundUseKeywords)) {
        if (memberFundUse.includes(key)) {
          partialMatch = grantEligibleUses.some(gu =>
            synonyms.some(s => gu.includes(s)) || gu.includes(key)
          );
          if (partialMatch) break;
        }
      }
    }

    if (directMatch) {
      dimensions.fundUse = { score: 10, max: 10, detail: 'Fund use directly matches' };
    } else if (partialMatch) {
      dimensions.fundUse = { score: 5, max: 10, detail: 'Fund use partially matches' };
      improvements.push({
        dimension: 'Fund Use',
        text: 'Your planned fund use partially aligns. Review the grant\'s eligible activities to see if your specific plans qualify.',
        effort: '10 minutes reading grant details'
      });
    } else {
      dimensions.fundUse = { score: 0, max: 10, detail: 'Fund use does not match grant requirements' };
      improvements.push({
        dimension: 'Fund Use',
        text: `This grant funds: ${grantEligibleUses.join(', ')}. Consider whether your project could be framed to align with these uses.`,
        effort: 'Requires reviewing your project scope'
      });
    }
  }

  // ---- CALCULATE TOTAL ----
  let totalScore = 0;
  for (const dim of Object.values(dimensions)) {
    totalScore += dim.score;
  }

  // ---- SORT IMPROVEMENTS by ease ----
  const effortOrder = {
    '5 minutes': 1,
    '10 minutes': 2,
    '15 minutes': 3,
    '30 minutes': 4,
    'Quick check': 5,
    'Requires reviewing': 6,
    'Not actionable': 99
  };

  improvements.sort((a, b) => {
    const aOrder = Object.entries(effortOrder).find(([k]) => a.effort.includes(k))?.[1] || 50;
    const bOrder = Object.entries(effortOrder).find(([k]) => b.effort.includes(k))?.[1] || 50;
    return aOrder - bOrder;
  });

  return {
    totalScore,
    dimensions,
    excluded,
    exclusionReason,
    improvements: improvements.map(i => `${i.text} (${i.effort})`)
  };
}

/**
 * Build a memberProfile object from combined intake data.
 * Takes business basics (user_intake) and grant radar intake (grant_radar_intake).
 */
function buildMemberProfile(businessBasics, grantIntake) {
  const bb = businessBasics || {};
  const gi = grantIntake || {};

  return {
    // From business basics
    businessName: bb.business_name || gi.q1_legal_name,
    businessType: bb.industry || '',
    businessDescription: bb.business_description || gi.q5_business_description || '',
    state: bb.state || '',
    city: bb.city || '',

    // Exact numbers (prefer grant intake, fall back to business basics)
    annualRevenue: gi.q8_annual_revenue != null ? gi.q8_annual_revenue : (bb.exact_revenue || 0),
    employeeCount: gi.q9_employee_count != null ? gi.q9_employee_count : (bb.exact_employee_count || 1),

    // Entity type
    legalStructure: gi.q11_legal_structure || bb.legal_entity || '',

    // NAICS
    naicsCode: gi.q20_naics_code || bb.naics_code || '',

    // Demographics
    ownerDemographics: gi.q12_owner_demographics || bb.owner_demographics || [],

    // Registrations
    samRegistered: gi.q3_sam_registered || bb.sam_registration || 'no',
    hasEIN: gi.q2_has_ein || 'unsure',

    // Fund use
    primaryFundUse: gi.q7_primary_fund_use || bb.grant_fund_use || '',

    // Additional context
    yearsOperating: gi.q10_years_operating || bb.years_operating || '',
    hasSeparateBankAccount: gi.q13_separate_bank_account || 'unknown',
    hasBusinessPlan: gi.q15_business_plan || 'unknown',
    priorGrants: gi.q18_prior_grants || 'unknown',

    // Branch-specific
    conductsRD: gi.q21_conducts_rd,
    hasIP: gi.q22_has_ip,
    universityPartnerships: gi.q23_university_partnerships,
    facility: gi.q25_facility,
    isNonprofit: normalizeEntityType(gi.q11_legal_structure || bb.legal_entity) === 'nonprofit',
    isRural: (gi.q12_owner_demographics || bb.owner_demographics || []).some(
      d => d.toLowerCase().includes('rural')
    ),
    isDistressed: (gi.q12_owner_demographics || bb.owner_demographics || []).some(
      d => d.toLowerCase().includes('distressed') || d.toLowerCase().includes('opportunity zone')
    ),
    communityServicePrograms: gi.community_service_programs || ''
  };
}

module.exports = {
  calculateGrantMatch,
  buildMemberProfile,
  normalizeEntityType,
  getNAICSSector,
  inferNAICSSectors
};
